### ISSUE TITLE
Подскажите где тесты и почему не работает CI

### ISSUE THREAD

**Issue by MBkkt** [vk-airline/airline-crm#4]
Я не очень понял есть ли тесты на это. Так как кажется корректность достаточно важна

**Comment by issokov** [comment]
Привет, тесты здесь: https://github.com/vk-airline/airline-crm/blob/main/crm/tests.py
CI не работал, т.к. после одного из коммитов не хватало переменной среды и тесты валились, т.к. система отказывала в работе с ней.
